version: "3"
services:
  sonarqube:
    image: sonarqube:8.9.7-community
    container_name: sonarqube-server
    depends_on:
      - db
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "80:9000"
    ### A SonarQube instance will stop gracefully, waiting for any tasks in progress to finish. 
    ### Waiting for in-progress tasks to finish can take a large amount of time which the docker does not expect by default when stopping. 
    stop_grace_period: 3600s
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "5"
    
  # sonarqube-cli:
  #   image: sonarsource/sonar-scanner-cli
  #   container_name: sonarqube-cli
  #   volumes:
  #     - "${YOUR_REPO}:/usr/src"
  #   tty: True
  #   command: bash
  #   network_mode: "service:sonarqube"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    stop_grace_period: 3600s
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "5"

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data: